apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpreApPVFF4TVROYUZ3MDBNekF4TWpreE9UUXhNVE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEaEJTUmFkYittN2h6SW1HajdoVm9DM3FJa2M1WVovR1J2QnM1Uzh2VFE0SUp5OXdHTwpIWUdET012R1UxZ2hNbkJUTm9vUEdJU1NtcXg0T2p1b09kNmNsZ05sTXZnOXV4SEp1N0ViUENSdW8vT0VuVW5oClc1NlhvOUlPRmJEY3hKRklzUlNkaHowdkF5ZHd5RmRKdU9mRzdwM00wbTRmTzdiRE9KcVkvQjdXL1VzdTVyNEQKR1VIK2lRcHFqLytydSs3ZUhIcUpZMklrQ2grVGxNV3RFL3hGMUlQYXhabGFXSUhYUjdrRzM3MW40bzNDWGhJOQp4YkllWEhBcDZFRDhhaVFaSXZXYWdWYVhrT2JtQlEwNWNvYW85OENCUko5V1E3SDc3a2hMQlhiV2FudFV1d29hCjZDWUovTU9reGRwbkJ1MURNOXF2Nys1RzRCYUFsb3F2OEpJbEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlEvNHFuV0JnTTdIWTdMS2RtNgo3eEU4QWhVL2FqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFwMUlpZElFVEUzM2NoSnhkQlppVUNGUTlwRDNlCnh0NXZ6WTJpN1lDYnJHd3I0QlVhS2N3dExDb2RBOUhMNjFBdVgwaGZ2UnJ0SkJRQjhlU1dqYWw5UDdGN1ErOHIKT3hWdTUyUGp2THJYd0tUWk1MV0hwVWdyVjdjdXlQc21iNUJMc05PSVR5a0tLOHRiMEpPS0VWS0dSWElUNUo0NApHUVdLbDNkK2t5RFUxZjZNaUNJaWE2bU8rQVJ5SG5HR0pOUWhFQXdGeGtDbmEzWlh1Yk1xaVBXS2k3M2lCUStRCmdENW9GZ3o3RmFqVUgzZysxQW1OckdMZXc2QTBCdnE0NUxpVTZFSUNiTkpEOHYwK1VvRlRwYlRzSFlicWtySnMKazFPbTh0aUlVV2U1U2pzY1gvVFRHcEF3SGplNWJxM2NYNGE4THBoV0V3YnJHclIvWXVqdURFd3BzUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5dd25ead-499e-4e98-8402-430fcc3108d9.k8s.ondigitalocean.com
  name: do-nyc1-kubernetes
contexts:
- context:
    cluster: do-nyc1-kubernetes
    user: do-nyc1-kubernetes-admin
  name: do-nyc1-kubernetes
current-context: do-nyc1-kubernetes
users:
- name: do-nyc1-kubernetes-admin
  user:
    token: dop_v1_6c47a7f8479c75e1a96631d58afe2f72502d5de3592d7b6f779b87313798e5a7
